
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.util.Date;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nikit
 */
public class IssueBook extends javax.swing.JFrame {
    
            Connection conn = Connect.getConnection();
            PreparedStatement pst = null;
            ResultSet rs = null;
            
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IssueBook.class.getName());

    /**
     * Creates new form IssueBook
     */
    public IssueBook() {
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        Date d;
        d = new Date();
        txtissuedate.setText(sdf.format(d));
        
        Calendar cal = Calendar.getInstance();
        cal.setTime(d);
        cal.add(Calendar.DAY_OF_MONTH, 7);

        Date due = cal.getTime();
        txtduedate.setText(sdf.format(due));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtissuedate = new javax.swing.JTextField();
        txtduedate = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtstudentid = new javax.swing.JTextField();
        txtbookid = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        btnissue = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 0, 51, 48));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stack-of-books.png"))); // NOI18N
        jLabel1.setText("Issue Book");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 352, 64));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Book ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 125, 36));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Student ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 125, 36));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Book Name :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 125, 36));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Due Date :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 125, 36));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Issue Date :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 125, 36));

        txtissuedate.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 262, 44));

        txtduedate.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtduedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 262, 44));

        txtbookname.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 262, 44));

        txtstudentid.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 262, 44));

        txtbookid.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 262, 44));

        btnsearch.setBackground(new java.awt.Color(204, 0, 0));
        btnsearch.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(255, 255, 255));
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        btnissue.setBackground(new java.awt.Color(0, 204, 102));
        btnissue.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnissue.setForeground(new java.awt.Color(255, 255, 255));
        btnissue.setText("Issue");
        btnissue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnissueActionPerformed(evt);
            }
        });
        getContentPane().add(btnissue, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 119, 47));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download (1).jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 630, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnissueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnissueActionPerformed
        // TODO add your handling code here:
        if(txtbookid.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter book id and search it");
            txtbookid.requestFocus();
        }
            else if(txtstudentid.getText().equals("")){
            JOptionPane.showMessageDialog(this,"All fields are required");
            txtbookid.requestFocus();
                    }
        else{
            try {
                pst = conn.prepareStatement("UPDATE book SET status=?,issuedate=?,duedate=?,studentid=? WHERE id=?;");
                pst.setString(1,"ISSUED");
                pst.setString(2,txtissuedate.getText());
                pst.setString(3,txtduedate.getText());
                pst.setString(4,txtstudentid.getText());
                pst.setString(5,txtbookid.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Book Issued");
                txtbookid.setText("");
                txtbookname.setText("");
                txtstudentid.setText("");
                txtissuedate.setText("");
                txtduedate.setText("");
            } catch (SQLException ex) {
                System.getLogger(IssueBook.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        
    }//GEN-LAST:event_btnissueActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        if(txtbookid.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please enter book id and search it");
            txtbookid.requestFocus();
        }
        else{
            try {
                pst = conn.prepareStatement("SELECT * FROM book WHERE id=?;");
                pst.setString(1,txtbookid.getText());
                rs = pst.executeQuery();
                if(rs.next()){
                    txtbookname.setText(rs.getString(2));
                }
                else{
                    JOptionPane.showMessageDialog(this,"Book not found");
                    txtbookid.setText("");
                }
            } catch (SQLException ex) {
                System.getLogger(IssueBook.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
        
    }//GEN-LAST:event_btnsearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IssueBook().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnissue;
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtduedate;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtstudentid;
    // End of variables declaration//GEN-END:variables
}
