
import java.sql.*;
import javax.swing.JOptionPane;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nikit
 */
public class StudentRegistration extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentRegistration.class.getName());

    /**
     * Creates new form StudentRegistration
     */
    public StudentRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtcourse = new javax.swing.JTextField();
        txtbranch = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtsemester = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/close icon.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 0, 48, 46));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/stack-of-books.png"))); // NOI18N
        jLabel1.setText("Student Registration");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 310, 60));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Student Name : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 237, 145, 42));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setText("Course :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 297, 145, 42));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setText("Branch : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 357, 145, 42));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setText("Student ID : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 177, 145, 42));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("Semester : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 417, 145, 42));

        txtid.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 177, 283, 42));

        txtcourse.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtcourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 297, 283, 42));

        txtbranch.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 357, 283, 42));

        txtname.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 237, 283, 42));

        txtsemester.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        getContentPane().add(txtsemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 417, 283, 42));

        btnsave.setBackground(new java.awt.Color(0, 204, 102));
        btnsave.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnsave.setForeground(new java.awt.Color(255, 255, 255));
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 516, 131, 49));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/download (1).jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 630, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        if(txtid.getText().equals("")){
            JOptionPane.showMessageDialog(this,"All fields are required");
        txtid.requestFocus();
        }
        else if(txtname.getText().equals("")){
            JOptionPane.showMessageDialog(this,"All fields are required");
        txtname.requestFocus();
                }
        else if(txtcourse.getText().equals("")){
            JOptionPane.showMessageDialog(this,"All fields are required");
        txtcourse.requestFocus();
                }
        
        else if(txtbranch.getText().equals("")){
            JOptionPane.showMessageDialog(this,"All fields are required");
        txtbranch.requestFocus();
                }
        else if(txtsemester.getText().equals("")){
            JOptionPane.showMessageDialog(this,"All fields are required");
        txtsemester.requestFocus();
                }
        else{
            try {
                Connection c = Connect.getConnection();
                PreparedStatement check = c.prepareStatement("SELECT * FROM student WHERE id=?;");
                check.setString(1,txtid.getText());
                ResultSet rs = check.executeQuery();
                if(rs.next())
                    JOptionPane.showMessageDialog(this,"This Student ID already exists");
                else{
                PreparedStatement pst = c.prepareStatement("INSERT INTO student (id,name,course,branch,semester)VALUES(?,?,?,?,?);");
                pst.setString(1,txtid.getText());
                pst.setString(2,txtname.getText());
                pst.setString(3,txtcourse.getText());
                pst.setString(4,txtbranch.getText());
                pst.setString(5,txtsemester.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Record Saved!");
                txtid.setText("");
                txtname.setText("");
                txtcourse.setText("");
                txtbranch.setText("");
                txtsemester.setText("");
            }
            }catch (SQLException ex) {
                System.getLogger(StudentRegistration.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            
    }//GEN-LAST:event_btnsaveActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentRegistration().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtbranch;
    private javax.swing.JTextField txtcourse;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtsemester;
    // End of variables declaration//GEN-END:variables
}
